name: setup-environment
author: Yuuki
description: Sets up the Java development environment with JDK 21 and caches the Maven repository.
runs:
  using: "composite"
  steps:
    - name: Set MAVEN_OPTS to use local Maven repo
      run: |
        echo "MAVEN_OPTS=-Dmaven.repo.local=${HOME}/.m2/repository" >> $GITHUB_ENV
      shell: bash

    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Cache Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-m2-
