exterminator3618.port=36018
spring.datasource.url=jdbc:mysql://localhost:3306/exterminator3618
spring.datasource.username=exterminator3618
spring.datasource.password=testpassword101
spring.jpa.hibernate.ddl-auto=update