name: Build JAR executable
on:
#  push:
#    branches-ignore:
#      - master
  pull_request:
    branches:
      - master
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-desktop-jar:
    name: Build Desktop JAR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Build Desktop JAR
        run: |
          mvn -B -f ./pom.xml clean install
          mvn -B -f ./desktop/pom.xml package

      - name: Upload Desktop JAR artifact
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: desktop-jar-${{ github.sha }}
          path: |
            ./desktop/target/*.jar
            !./desktop/target/original-*.jar

      - name: Upload Desktop JAR to GitHub Releases
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          find ./desktop/target -maxdepth 1 -type f -name 'original-*.jar' -delete
          gh release upload ${{ github.event.release.tag_name }} ./desktop/target/*.jar --clobber

  build-server-jar:
    name: Build Server JAR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Build Server JAR
        run: |
          mvn -B -f ./server/pom.xml clean package spring-boot:repackage

      - name: Upload Server JAR artifact
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: server-jar-${{ github.sha }}
          path: |
            ./server/target/*.jar

      - name: Upload Server JAR to GitHub Releases
        if: github.event_name == 'release'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            gh release upload ${{ github.event.release.tag_name }} ./server/target/*.jar --clobber
