name: Run Tests
on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test_all:
    name: Run all tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: Run tests
        run: mvn -B test

      - name: Report test results
        if: always()
        uses: dorny/test-reporter@v2
        with:
          name: unit-tests
          path: ./*/target/surefire-reports/*.xml
          reporter: java-junit
